### ISSUE TITLE
[Problem] Error when compressing logs on latest WIP

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/MPF#414] opened 2022-10-17 23:36 UTC
[console.log](https://github.com/SabreTools/MPF/files/9805160/console.log)

```
...
Compressing log files...
Compression could not complete: System.TypeInitializationException: The type initializer for 'System.Text.BaseCodePageEncoding' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Text.BaseCodePageEncoding.ReadCodePageDataFileHeader(Stream stream, Byte[] codePageDataFileHeader)
   at System.Text.BaseCodePageEncoding.GetEncodingDataStream(String tableName)
   at System.Text.BaseCodePageEncoding..cctor()
   --- End of inner exception stack trace ---
   at System.Text.BaseCodePageEncoding.GetCodePageByteSize(Int32 codePage)
   at System.Text.CodePagesEncodingProvider.GetEncoding(Int32 codepage)
   at System.Text.CodePagesEncodingProvider.GetEncoding(Int32 codepage)
   at System.Text.EncodingProvider.GetEncodingFromProvider(Int32 codepage)
   at System.Text.Encoding.GetEncoding(Int32 codepage)
   at System.IO.Compression.ZipArchiveEntry.EncodeEntryName(String entryName, Boolean& isUTF8)
   at System.IO.Compression.ZipArchiveEntry.set_FullName(String value)
   at System.IO.Compression.ZipArchiveEntry..ctor(ZipArchive archive, String entryName)
   at System.IO.Compression.ZipArchive.DoCreateEntry(String entryName, Nullable 1 compressionLevel)
   at System.IO.Compression.ZipFileExtensions.DoCreateEntryFromFile(ZipArchive destination, String sourceFileName, String entryName, Nullable 1 compressionLevel)
   at System.IO.Compression.ZipFileExtensions.CreateEntryFromFile(ZipArchive destination, String sourceFileName, String entryName)
   at MPF.Library.InfoTool.CompressLogFiles(String outputDirectory, String outputFilename, BaseParameters parameters) in C:\projects\mpf\MPF.Library\InfoTool.cs:line 616
Submission information process complete!
```

**Comment by mnadareski** [comment] 2022-10-17 23:43
Attempted fixes at:
https://github.com/SabreTools/MPF/commit/e0f8443653947c940f0644aed3072173b20f0dda
https://github.com/SabreTools/MPF/commit/5f059253a4ace673f496868e4eb02201b3ba2a6f

**Comment by mnadareski** [comment] 2022-10-18 00:17
Neither fix worked. The issue is happening withing SharpCompress. I will look into alternatives such as using `System.Compression` instead.

**Comment by mnadareski** [comment] 2022-10-18 04:04
Above attempted fixes rolled back with https://github.com/SabreTools/MPF/commit/b57e0bb97e8255c0c7497f5aea6a7490db6e8f81

**Comment by mnadareski** [comment] 2022-10-18 04:05
Another attempted fix: https://github.com/SabreTools/MPF/commit/7c411d36dbd5b574f1933e9de44cd3cdfd116d5f

**Comment by mnadareski** [comment] 2022-10-18 20:31
Fixed as of https://github.com/SabreTools/MPF/commit/7c411d36dbd5b574f1933e9de44cd3cdfd116d5f

**Closed by mnadareski** 2022-10-18 20:31 UTC
Labels: bug
