### ISSUE TITLE
When MPF or MPF.check is requesting data from Redump, it times out and hangs

### ISSUE THREAD

**Issue by sadikyo** [SabreTools/MPF#249] opened 2020-12-29 18:51 UTC
Tested on multiple builds and multiple NET frameworks, latest stable and WIP:

When MPF or Check is trying to pull data from redump via a user login, if there is a delay or timeout (on the redump side), MPF or check fails.  For MPF, it just hangs and doesn't generate the submission window.  

Ideally, if some sort of timer could be enabled, and the pull cancelled, then you could at least finish the dump successfully and manually fill in the submission window.  

Check is slightly less of a problem - it's pretty quick and just throws an error and moves on.

**Comment by mnadareski** [comment] 2020-12-29 19:11
Possibly addressed in https://github.com/SabreTools/MPF/commit/f96d4ee37e1924a2f14d7d1c6809508123ea7c39

Unfortunately, the root cause is having to use regular HTTP methods to retrieve data from Redump to fill in information. If there were an API, I'd be able to have a much cleaner flow.

**Comment by mnadareski** [comment] 2020-12-30 22:18
According to the people affected, this has been fixed, sans the actual issues connecting to Redump.

**Closed by mnadareski** 2020-12-30 22:18 UTC
Labels: bug
