### ISSUE TITLE
[Problem] Freezing & Opening Submission Info window before finished scanning

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/MPF#364] opened 2022-02-09 04:39 UTC
**Version**
- [x] Stable release (2.3)

**Build**
- [X] .NET Framework 4.8 running on (Operating System)

**Describe the issue**
Frozen Disc Information window while scanning. You can see the scanning numbers change in the two images while the Disc Info window is open. The Disc Info window is unresponsive and MPF freezes entirely after. Disabling archive scanning prevents this from happening.

**Screenshots**
https://media.discordapp.net/attachments/461797735427735562/940795918209392660/unknown.png
https://media.discordapp.net/attachments/461797735427735562/940795982277398578/unknown.png

**Additional context**
May be related to Blizzard's MPQ archives and how BOS handles it.

**Comment by mnadareski** [comment] 2022-02-16 21:54
I finally ran into this myself and it was what I expected. The internal queues get overloaded and need to flush. The reason I didn't notice before is that I kept the ejection reminder enabled locally, which basically allows for the queue to catch up before the info screen is shown. I will be closing this since it's not a bug, rather an unintended side-effect of a poorly-designed queueing system.

**Closed by mnadareski** 2022-02-16 21:54 UTC
Labels: bug
