### ISSUE TITLE
[Problem] Log output background color changed to white during a dump

### ISSUE THREAD

**Issue by SilasLaspada** [SabreTools/MPF#283] opened 2021-05-24 13:45 UTC
**Version**
What version are you using? 

- [ ] Stable release (version here)
- [X] WIP release 2.0-ebaf9539

**Build**
What runtime version are you using?

- [ ] .NET Framework 4.7.2 running on (Operating System)
- [ ] .NET Framework 4.8 running on (Operating System)
- [ ] .NET Core 3.1 running on (Operating System)

**Describe the issue**
The background color of the log output suddenly turned white during a dump.

**To Reproduce**
Unknown 

**Screenshots**
![MPF_7i2dZU94Gb](https://user-images.githubusercontent.com/24215969/119356667-ee41b580-bc63-11eb-91ac-28d33b80749d.png)
![MPF_IMA1BDg950](https://user-images.githubusercontent.com/24215969/119356686-f26dd300-bc63-11eb-874d-149948b9fbab.png)

**Comment by mnadareski** [comment] 2021-06-19 22:48
I have not been able to reproduce this. @SilasLaspada if you are able to reproduce reliably, please reopen this. Otherwise, I'm tagging as a wontfix because there's no way to make it happen again.

**Comment by mnadareski** [comment] 2021-07-18 03:24
@IcySon55 was able to help narrow down this error and it was able to be reproduced by sending a ton of data at the log. A fix was tested and will be in soon.

**Closed** 2021-07-18 03:35 UTC
Labels: bug
