### ISSUE TITLE
[Problem] submissioninfo.txt reporting disc type twice

### ISSUE THREAD

**Issue by FoxhackDN** [SabreTools/MPF#509] opened 2023-06-30 07:39 UTC
**Version**
What version are you using? 

- [ ] Stable release (version here)
- [*] WIP release (2.5-1146)

**Build**
What runtime version are you using?

- [*] .NET Framework 4.8 running on Windows 10
- [ ] .NET 6.0 running on (Operating System)

**Describe the issue**
The disc type, as reported in the submission info, is randomly doubled. I dumped four different DVD-Video games and two of them had "Reported Disc Type: DVD-ROM, DVD-ROM" in the submission info at the very end; the other two only mentioned it once. Out of sixteen different DVD Video discs I've dumped in the past couple of days, three (maybe more) showed this issue.

I thought this might be related to the discs having two layers, but one of my dual layer dumps (with a file size of 8170846208) does not exhibit this problem. The others have file sizes of 7830910976, 7997978624, and 7362422784.

**To Reproduce**
Dump a DVD Video disc.

**Expected behavior**
"DVD-Rom" being listed once.

**Comment by mnadareski** [comment] 2023-07-06 15:06
Duplicate of https://github.com/SabreTools/MPF/issues/418 even if it's a different disc type.

**Closed by mnadareski** 2023-07-06 15:06 UTC
Labels: bug, duplicate
