### ISSUE TITLE
[Info] Unsure how to use --load-seed feature in MPF.Check

### ISSUE THREAD

**Issue by JohnVeness** [SabreTools/MPF#729] opened 2024-07-23 14:15 UTC
Hi. I am investigating the --load-seed feature in MPF.Check, which at first glance sounds like it will be useful for entering barcodes, ringcodes etc., but I am unsure if I am using it correctly.

I have created a file called !submissionSeed.json containing:
`{
  "schema_version": 3,
  "common_disc_info": {
    "d_number": "",
    "d_label": "",
    "d_languages": [],
    "d_languages_selection": [],
    "d_serial": "SLES-52017",
    "d_ring_0_ma1": "Sony DADC   A0100486277-A511   17",
    "d_ring_0_ma1_sid": "IFPI L557",
    "d_ring_0_ts1": "B1",
    "d_ring_0_mo1_sid": "IFPI 941Z",
    "d_ring_0_mo1": null,
    "d_ring_0_ma2": null,
    "d_ring_0_mo2_sid": null,
    "d_ring_0_ma3": null,
    "d_ring_0_ma4": null,
    "d_ring_0_offsets": "1",
    "d_ring_count": "1",
    "d_barcode": "5 030930 035105",
    "d_comments": "[T:ISN] SLES-52017\n[T:EAID] EAE03404473IS (Cover), EAE03404073D (Disc), EAE03404073M (Manual)",
    "d_contents": "(I haven't checked this)"
  },
  "versions_and_editions": {
    "d_editions_text": "Original"
  }
}`

and done:

`MPF.Check dvd ps2 -u redumper -l \!submissionSeed.json LOTRRK.log`

but the resultant !submissionInfo.txt and !submissionInfo.json files are the same as if I hadn't included the -l option, that is, they still have "(REQUIRED, IF EXISTS)" instead of the ringcodes etc. I put in the seed file.

Have I got the format of the seed file correct?

**Comment by Deterous** [comment] 2024-07-23 15:01
Duplicate of #730

**Closed by Deterous** 2024-07-23 15:01 UTC
Labels: question
