### ISSUE TITLE
[Problem] PS3 Media Type output BD-ROM-25 when it was BD-ROM-50

### ISSUE THREAD

**Issue by Ragowit** [SabreTools/MPF#408] opened 2022-09-28 19:08 UTC
**Version**
- [x] WIP release (2.3-60d5a117)

**Build**
- [x] .NET Framework 4.8 running on (Win 11 22H2)

**Describe the issue**
Dump "Beyond: Two Souls" (PS3), the generated output will say BD-ROM-25 and it's actually a BD-ROM-50. Layerbreak info is also missing.

**To Reproduce**
1. Pop in Beyond: Two Souls (PS3) game into your optical drive
2. Dump it
3. Read the submission text file

**Expected behavior**
To output BD-ROM-50 when it's such a disc, with layerbreak info.

**Comment by mnadareski** [comment] 2022-09-28 19:14
Duplicate of https://github.com/SabreTools/MPF/issues/399

**Closed by mnadareski** 2022-09-28 19:14 UTC
Labels: duplicate
