### ISSUE TITLE
[Request] ability to recall submission info window

### ISSUE THREAD

**Issue by gingerbeardman** [SabreTools/MPF#318] opened 2021-10-22 12:23 UTC
**Is your feature request related to a problem? Please describe.**

Sometimes I dismiss the Submission Info window with an erroneous press of return/enter.

**Describe the solution you'd like**

I'd like to recall the Submission Info window.

It doesn't even need to be populated, as it was dismissed prematurely I'd be willing to enter all information again from the beginning.

**Describe alternatives you've considered**

Edit submission text file by hand.

**Comment by mnadareski** [comment] 2022-01-04 19:19
Partially addressed by https://github.com/SabreTools/MPF/commit/9e4af1d66bf539d5e10d4b9743c7eacaa13f711c

**Comment by JohnVeness** [comment] 2022-02-15 17:37
> The other proposed thing that I'm more willing to deal with is a half-way between current MPF and Check that pops up the UI so it can be run separately after.

I wonder if this proposed thing would solve a problem I have, where I foolishly deleted the !submissionInfo.txt file, but still have the zipped logs. It would be great to recreate !submissionInfo.txt from the logs, assuming everything is somewhere in the logs.

**Comment by mnadareski** [comment] 2022-02-15 17:43
@JohnVeness If you unzip the files in that folder and then make dummy versions of the IMG/SCM (if it's a CD), then you can just use MPF.Check to create a mostly-complete version of the submissionInfo file. Then it can be filled in by hand with things like ringcodes. See the wiki or the built-in help text in MPF.Check for more details.

**Comment by mnadareski** [comment] 2023-10-11 01:35
I'm now considering this a duplicate of https://github.com/SabreTools/MPF/issues/466 for the sake of ease.

**Closed by mnadareski** 2023-10-11 01:35 UTC
Labels: enhancement
