### ISSUE TITLE
[Request] Option to disable Enter Key detection when typing submission info

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/MPF#278] opened 2021-05-19 19:40 UTC
**Is your feature request related to a problem? Please describe.**
I'm a sloppy typist and my nail often catches the enter button when I hit shift, and sometimes I don't realize my cursor isn't in the info box.

**Describe the solution you'd like**
Toggle-able option in settings to disable enter key detection when typing submission info.

**Describe alternatives you've considered**
Getting better at typing, but I don't think that's going to happen.

**Additional context**
Additional context

**Comment by mnadareski** [comment] 2021-05-20 17:07
As mentioned in Discord, this might be possible to implement, but I may push this off for a long time since I'd claim that it's expected behavior.

**Comment by mnadareski** [comment] 2022-01-04 19:13
Fixed by https://github.com/SabreTools/MPF/commit/9e4af1d66bf539d5e10d4b9743c7eacaa13f711c

**Closed by mnadareski** 2022-01-04 19:13 UTC
Labels: enhancement, help wanted
